### PR TITLE
Dynamic fontFamily name

### PR DESCRIPTION
**Pull request by qkdreyer**

### CODE REVIEW

**Comment by Yuyz0112** [comment]
Thanks for the PR.
What's the use case of change the name of the zip file?

**Comment by qkdreyer** [comment]
In order to support the "preferences.fontPref.metadata.fontFamily" parameter value from the [selection.json](../blob/master/test-assets/selection-empty.json#L16) file.

**Comment by Yuyz0112** [comment]
@qkdreyer published in `1.3.0`

**Comment by qkdreyer** [comment]
Thanks !

**Pull request merged**
